### ISSUE TITLE
Clarify motivation vs. pmtiles

### ISSUE THREAD

**Issue by heyarne** [versatiles-org/versatiles-rs#24]
Hey, just found this after watching the introduction at fossgis.

Can you clarify why you defined a new format, and where exactly the differences to https://github.com/protomaps/go-pmtiles lie? I already looked at pmtiles and was quite intrigued by the idea to just put your vector tiles somewhere and query it via range queries. From what I can tell versatiles is pretty similar in that regard?

**Comment by MichaelKreil** [comment]
The core concept of PMTiles (and COMTiles) is to use a "serverless" architecture to serve map tiles. While the idea is intriguing, it comes with several challenges. In particular, the inability to use HTTP compression and HTTP caching, limited HTTP CORS, and high latency make PMTiles less suitable for scalable infrastructures. To address these issues, we decided to take the opposite approach with VersaTiles.

VersaTiles uses a server-based architecture for tile hosting, as opposed to the serverless approach of PMTiles. This difference in approach may cause long-term tension between these two projects. Therefore, we need a standard that matches our approach and that we can adapt to the needs of our project.

It is worth noting that all three projects, COMTiles, PMTiles and VersaTiles, are based on the new idea of a tile container file format that can be accessed via HTTP range requests. This is a promising concept that deserves further exploration. We should avoid imposing unnecessary restrictions by mandating compatibility between totally different projects.

**Comment by bdon** [comment]
To echo what @MichaelKreil wrote, the PMTiles format and ecosystem is designed with “serverless” straight-to-the-browser consumption as a first-class use case. Users find this useful for dev environments and small-scale low maintenance projects. 

Accessing tiles in this way can be higher latency compared to alternatives, but this is more related to the underlying latency of cloud storage systems like S3 rather than the archive design itself. At scale the recommendation is to configure a [CDN integration](https://protomaps.com/docs/cdn) which is a small bit of open source code to help mitigate the mentioned drawbacks related to HTTP compression, latency, and CORS.

You can use PMTiles in a “serverful” way, accessing archives on disk, using the [go-pmtiles](https://github.com/protomaps/go-pmtiles) command line tool. But this isn’t the focus of development right now (although it might power serverless Azure/Google Cloud integrations). If running a tileserver fits your use case than VersaTiles or [mbtileserver](https://github.com/consbio/mbtileserver) may be a better fit.

**Comment by nyurik** [comment]
@MichaelKreil thanks for the write up, but if I read your arguments correctly, they all relate to the "serving" part, not to the actual "storage" part.  You are correct that having a server between the tile container and the user will improve things in many cases.  How does this relate to the container storage format?   In other words, if the container format is "good enough" (i.e. versatiles does not produce significantly faster or smaller overall files), and even the COM tiles project is essentially dead due to PMTiles (with the author focusing on the tile format itself as part of the new [MLT spec](https://github.com/maplibre/maplibre-tile-spec)), why split the ecosystem?  Note that there is also a very good `MBTiles` container format that has served the other side of the container story - randomly-accessible/modifiable/patchable/..., but lacking in HTTP-Range accessibility.

**Comment by MichaelKreil** [comment]
First: We support all major container formats: `*.versatiles`, `*.pmtiles` and `*.mbtiles` - we even support `*.tar` files and Z/X/Y directories. So we are not forcing anyone to use our container.

But `*.versatiles` containers have a unique killer feature: The format supports very fast [partial downloads](https://github.com/versatiles-org/versatiles-documentation/blob/main/guides/download_tiles.md#partial-download). For example, if you want to run your own map server, but only need map data for a city or country, versatiles allows you to download only the tiles defined by a bounding box.
The complete installation process to set up a map server, including frontend and map data for your city takes less than 10 seconds:

https://github.com/user-attachments/assets/23059dcc-96da-47bd-b344-137163b092ed

There is also an experimental interactive installation guide that allows you to select a subset of a bounding box: https://versatiles.org/apps/setup_server

**Comment by nyurik** [comment]
@bdon would pmtiles allow similar type of range requesting?  E.g. user can simply say "download tiles with zxy in a bbox", and pmtiles would use optimized range requests to get just these tiles, rather than getting individual tiles?

**Comment by nyurik** [comment]
P.S. @MichaelKreil I don't doubt you like the technology, and I am glad you are thinking in terms of killer features.  We just need to make sure there **is** a significant difference in terms of features / performance / size to make the distinction clear to the users - so they know when to choose which and why.

**Comment by bdon** [comment]
> @bdon would pmtiles allow similar type of range requesting? E.g. user can simply say "download tiles with zxy in a bbox", and pmtiles would use optimized range requests to get just these tiles, rather than getting individual tiles?

Yes via `pmtiles extract`, see intro at https://docs.protomaps.com/guide/getting-started#_3-extract-any-area and CLI docs: https://docs.protomaps.com/pmtiles/cli#extract

**Comment by MichaelKreil** [comment]
This is true, and works quite efficiently since PMTiles container version 3, but only if the `clustered` tile order was used when generating the source container.

**Comment by nyurik** [comment]
@MichaelKreil i suspect anyone who wants to allow sub-segment direct downloads would do use clustered, right? Could you think of any other differentiating factors? Thx!

**Comment by MichaelKreil** [comment]
Sorry for the delay - I've been really [busy](https://www.spiegel.de/international/business/we-know-where-you-parked-massive-data-breach-at-vw-raises-questions-about-vehicle-privacy-a-4b1cb926-2edb-42ea-92fb-5000cd378fc5) the last few weeks.

I wanted to follow up on the discussion about the use of PMTiles. While I appreciate PMTiles and the work that has gone into it, it does not fit with some of the long term goals of VersaTiles. Specifically:
1. PMTiles is very cloud storage oriented. VersaTiles, on the other hand, targets server-based architectures. A container format that's deeply tied to cloud usage wouldn't fully serve our requirements.
2. VersaTiles may need container features that PMTiles doesn't currently provide, such as
   - Multiple layers in a single container (e.g. combining vector OSM tiles and raster elevation tiles in a single container).
   - Different tile ordering for performance reasons or for specialised generation routines.
   - E.g. generating tiles from lower zoom levels upwards. (PMTiles is always top-down).
3. VersaTiles containers are a fundamental part of the VersaTiles stack. Dependence on an external container format driven by a different long-term roadmap introduces risks. If the PMTiles maintainers went in a direction that didn't fit the VersaTiles goals, we would have limited control. And if we wanted to go in a different direction, we would not be able to because we would be tied to PMTiles.
4. [PMTiles is owned by Protomaps LLC](https://github.com/protomaps/PMTiles/blob/main/LICENSE). While this is perfectly valid, I'm not entirely comfortable tying VersaTiles to a "product" owned by a company - especially when that company's business goals - or worse - its ownership might change unexpectedly. (You may have heard of Mapbox and its open source bait-and-switch strategy. 🙄 We have all learned our lesson.)
5. Also a minor issue: PMTiles is BSD 3-clause. Some aspects of that licence can be problematic. We'd prefer to have a container format that is completely under our own governance and licensing.

However, I'm not rejecting PMTiles. In fact, we plan to [improve support for "clustered" PMTiles] (https://github.com/versatiles-org/versatiles-rs/issues/83). But at this stage, VersaTiles has its own specialised container format because it provides the flexibility we need.
